# Generated by Django 3.1.2 on 2020-10-24 13:01

import awards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to=awards.models.user_directory_path, verbose_name='Pics')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='awards.project')),
            ],
        ),
    ]
