# Generated by Django 3.1.2 on 2020-10-24 15:22

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
