# Generated by Django 3.1.2 on 2020-10-25 09:58

import awards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20201025_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='project_description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=awards.models.user_directory_path, verbose_name='project_pic'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='images',
            field=models.FileField(null=True, upload_to=awards.models.user_directory_path, verbose_name='pics'),
        ),
    ]
