# Generated by Django 3.1.2 on 2020-10-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_auto_20201025_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='images',
            field=models.FileField(null=True, upload_to='images/', verbose_name='pics'),
        ),
    ]
