# Generated by Django 3.1.2 on 2020-10-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20201025_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='images',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='image_2',
            field=models.FileField(null=True, upload_to='image_2/', verbose_name='pics_2'),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='image_3',
            field=models.FileField(null=True, upload_to='image_3/', verbose_name='pics_3'),
        ),
    ]
