# Generated by Django 3.1.2 on 2020-10-26 07:25

import awards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0007_auto_20201025_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='project',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commenter_profile', to='awards.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='screenshots',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='awards.screenshot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to=awards.models.user_directory_path, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image_1',
            field=models.FileField(null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image_2',
            field=models.FileField(null=True, upload_to='image_2/', verbose_name='Second Image'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image_3',
            field=models.FileField(null=True, upload_to='image_3/', verbose_name='Third Image'),
        ),
    ]
