# Generated by Django 3.1.2 on 2020-10-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0008_auto_20201026_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='image_1',
            field=models.FileField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image_2',
            field=models.FileField(upload_to='image_2/', verbose_name='Second Image'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image_3',
            field=models.FileField(upload_to='image_3/', verbose_name='Third Image'),
        ),
    ]
