# Generated by Django 3.1.2 on 2020-10-26 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0014_auto_20201026_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater_profile', to='awards.profile'),
        ),
    ]
